ROWS = 12
COLS = 16
CELL_SIZE = 32
MINE_COUNT = 30
SOLVER_NAME = "solver.exe"

BOARD_PADDING = 20
TOP_BAR_HEIGHT = 90
BOTTOM_BAR_HEIGHT = 90

WINDOW_WIDTH = COLS * CELL_SIZE + BOARD_PADDING * 2
WINDOW_HEIGHT = ROWS * CELL_SIZE + TOP_BAR_HEIGHT + BOTTOM_BAR_HEIGHT + BOARD_PADDING * 2
WINDOW_TITLE = "Minesweeper"
FPS = 60
